'use strict';
const byId=id=>document.getElementById(id),escapeText=Church.escape;
let notices=[],manageMode=false,loading=false,lastIdentity='',subscribed=false,memberRows=[],memberQuery='',editingNotice=null;
function noticeStatus(n){if(!n.published)return 'Draft';if(new Date(n.publish_at)>new Date())return 'Scheduled';if(n.expires_at&&new Date(n.expires_at)<=new Date())return 'Expired';return 'Published';}
function drawNotices(){const q=byId('announcementSearch').value.trim().toLowerCase(),cat=byId('announcementCategory').value;const list=notices.filter(n=>(manageMode&&Church.isLeader()||noticeStatus(n)==='Published')&&(cat==='all'||n.category===cat)&&(!q||(n.title+' '+n.body).toLowerCase().includes(q)));byId('noticeCount').textContent=list.length+' announcement'+(list.length===1?'':'s')+(manageMode?' · leadership view':'');
 if(!Church.configured){byId('noticeFeed').innerHTML=Church.setupNotice();return;}
 byId('noticeFeed').innerHTML=list.length?list.map(n=>`<article class="notice-card ${n.pinned?'pinned':''} ${n.category==='Urgent'?'urgent':''}"><div class="notice-body"><div class="notice-tags"><span class="tag ${n.category==='Urgent'?'red':''}">${escapeText(n.category)}</span>${n.pinned?'<span class="tag gold">Pinned</span>':''}${noticeStatus(n)!=='Published'?`<span class="tag grey">${noticeStatus(n)}</span>`:''}</div><h2>${escapeText(n.title)}</h2><div class="notice-text">${escapeText(n.body)}</div></div><div class="notice-meta"><span>By ${escapeText(n.author_name)}</span><span>${noticeStatus(n)==='Scheduled'?'Scheduled for':'Published from'} ${escapeText(Church.date(n.publish_at))}</span>${n.version>1?`<span>Updated ${escapeText(Church.date(n.updated_at))}</span>`:''}${n.expires_at?`<span>Until ${escapeText(Church.date(n.expires_at))}</span>`:''}${Church.isLeader()?`<button class="church-btn" data-edit-notice="${n.id}">Edit / unpublish</button>`:''}</div></article>`).join(''):`<div class="empty-board"><h2>${q||cat!=='all'?'No matching announcements':'No published announcements yet'}</h2><p>${q||cat!=='all'?'Try a different search or category.':'Leadership notices will appear here once they are published. Check back while online for the latest updates.'}</p></div>`;
 document.querySelectorAll('[data-edit-notice]').forEach(b=>b.onclick=()=>openEditor(notices.find(n=>n.id===b.dataset.editNotice)));
}
async function fetchNotices(){if(!Church.client||loading)return;loading=true;try{const {data,error}=await Church.client.from('church_announcements').select('id,title,body,category,pinned,published,publish_at,expires_at,author_name,version,updated_at,created_at').order('pinned',{ascending:false}).order('publish_at',{ascending:false}).limit(200);if(error)throw error;notices=data||[];byId('connectionState').textContent='Connected · published updates refresh automatically';byId('connectionState').classList.remove('error');byId('lastUpdated').textContent='Last checked: '+Church.date(new Date());drawNotices();}catch(e){byId('connectionState').textContent='Unable to refresh — any displayed notices may be out of date';byId('connectionState').classList.add('error');if(!notices.length){byId('noticeFeed').innerHTML='<div class="empty-board"><h2>Noticeboard temporarily unavailable</h2><p>Check your internet connection. If this is a new installation, the website owner must finish the Supabase database setup.</p><button class="church-btn" id="retryNotices">Try again</button></div>';byId('retryNotices').onclick=fetchNotices;}}finally{loading=false;}}
byId('announcementSearch').oninput=drawNotices;byId('announcementCategory').onchange=drawNotices;
byId('newAnnouncement').onclick=()=>openEditor();byId('toggleManage').onclick=()=>{manageMode=!manageMode;byId('toggleManage').textContent=manageMode?'Show public view':'Show drafts & scheduled';drawNotices();};byId('refreshAnnouncements').onclick=fetchNotices;
function openEditor(n){if(!Church.isLeader()||!Church.online){Church.message('Only an online approved leader can publish announcements.');return;}editingNotice=n?{...n}:null;const d=byId('announcementDialog');
 d.innerHTML=`<div class="church-dialog-head"><h2 id="announcementDialogTitle">${n?'Edit announcement':'New announcement'}</h2><button class="church-icon-btn" id="closeAnnouncement" aria-label="Close editor">×</button></div><form id="announcementForm"><label for="noticeTitle">Title *</label><input id="noticeTitle" required maxlength="180" value="${escapeText(n?.title||'')}"><label for="noticeBody">Message *</label><textarea id="noticeBody" required maxlength="12000">${escapeText(n?.body||'')}</textarea><div class="two"><div><label for="noticeCategory">Category</label><select id="noticeCategory">${['General','Programme','Reminder','Urgent'].map(c=>`<option ${n?.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div><label for="noticePublishAt">Publish from (Zambia time) *</label><input id="noticePublishAt" type="datetime-local" required value="${Church.zambiaInput(n?.publish_at||new Date())}"></div><div><label for="noticeExpiresAt">Expiry (optional, Zambia time)</label><input id="noticeExpiresAt" type="datetime-local" value="${n?.expires_at?Church.zambiaInput(n.expires_at):''}"></div></div><label class="check-line"><input id="noticePinned" type="checkbox" ${n?.pinned?'checked':''}>Pin near the top of the noticeboard</label><label class="check-line"><input id="noticePublished" type="checkbox" ${n?.published?'checked':''}>Publish publicly (uncheck to keep as a draft or unpublish)</label><p class="editor-warning">Published announcements can be read by anyone. Do not include private pastoral, health, financial or contact records without appropriate permission. A future publish time schedules the notice.</p><p class="church-form-status" id="noticeSaveStatus" role="status"></p><div class="church-actions"><button type="submit" class="church-btn primary" id="saveAnnouncement">Save announcement</button><button type="button" class="church-btn" id="cancelAnnouncement">Cancel</button></div></form>`;
 byId('closeAnnouncement').onclick=()=>d.close();byId('cancelAnnouncement').onclick=()=>d.close();
 byId('announcementForm').onsubmit=async e=>{e.preventDefault();if(!Church.isLeader())return;const status=byId('noticeSaveStatus');const title=byId('noticeTitle').value.trim(),body=byId('noticeBody').value.trim(),publish=Church.isoFromZambia(byId('noticePublishAt').value),expires=Church.isoFromZambia(byId('noticeExpiresAt').value);if(!title||!body){status.textContent='Enter a title and message.';return;}if(expires&&new Date(expires)<=new Date(publish)){status.textContent='Expiry must be after the publish date and time.';return;}byId('saveAnnouncement').disabled=true;status.textContent='Saving…';try{const {error}=await Church.client.rpc('church_save_announcement',{p_id:editingNotice?.id||null,p_expected_version:editingNotice?.version||0,p_title:title,p_body:body,p_category:byId('noticeCategory').value,p_pinned:byId('noticePinned').checked,p_published:byId('noticePublished').checked,p_publish_at:publish,p_expires_at:expires});if(error)throw error;d.close();await fetchNotices();Church.message('Announcement saved. Only published, currently active notices appear in the public view.');}catch(err){status.textContent=err.message?.includes('CONFLICT')?'Another leader updated this announcement. Your text is still here: copy it before closing, then reopen the latest version.':err.message||'Save failed. Your text has not been discarded.';}finally{byId('saveAnnouncement').disabled=false;}};if(!d.open)d.showModal();
}
byId('manageMembers').onclick=async()=>{byId('membersPanel').hidden=!byId('membersPanel').hidden;if(!byId('membersPanel').hidden)await fetchMembers();};
async function fetchMembers(){if(!Church.isLeader())return;const {data,error}=await Church.client.from('church_members').select('user_id,display_name,email,approved,role,created_at').order('created_at',{ascending:false}).limit(500);if(error){Church.message('Unable to load member access requests: '+error.message);return;}memberRows=data||[];drawMembers();}
function drawMembers(){if(!Church.isLeader()){byId('membersPanel').hidden=true;return;}byId('membersPanel').innerHTML=`<div class="members-head"><h2>Member access</h2><button class="church-btn" id="closeMembers">Close</button></div><p class="church-muted" style="margin-bottom:15px">Approve only people whose identity you recognise. Members can read checklists. Leaders can edit programmes, read private registers, publish announcements and manage access.</p><input class="member-search" id="memberSearch" aria-label="Search access requests" placeholder="Find a name or email…" value="${escapeText(memberQuery)}"><div class="table-scroll"><table class="church-member-table"><thead><tr><th>Person</th><th>Access</th><th>Action</th></tr></thead><tbody id="memberRows"></tbody></table></div><p class="church-muted" style="margin-top:12px">At least one approved leader must remain. Revoking access stops future database reads; it cannot remove a copy someone already downloaded or printed.</p>`;byId('closeMembers').onclick=()=>byId('membersPanel').hidden=true;byId('memberSearch').oninput=e=>{memberQuery=e.target.value;drawMemberRows();};drawMemberRows();}
function drawMemberRows(){const q=memberQuery.trim().toLowerCase();byId('memberRows').innerHTML=memberRows.filter(m=>(m.display_name+' '+m.email).toLowerCase().includes(q)).map(m=>`<tr><td>${escapeText(m.display_name)}<small>${escapeText(m.email)}</small></td><td>${m.approved?(m.role==='leader'?'Leader':'Member (view only)'):'Pending / revoked'}</td><td><div class="church-actions">${!m.approved||m.role!=='viewer'?`<button class="church-btn" data-access-id="${m.user_id}" data-role="viewer" data-approved="true">Approve member</button>`:''}${!m.approved||m.role!=='leader'?`<button class="church-btn" data-access-id="${m.user_id}" data-role="leader" data-approved="true">Appoint leader</button>`:''}${m.approved?`<button class="church-btn danger" data-access-id="${m.user_id}" data-role="${m.role}" data-approved="false">Revoke access</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="3">No matching access requests.</td></tr>';
 document.querySelectorAll('[data-access-id]').forEach(b=>b.onclick=async()=>{const m=memberRows.find(x=>x.user_id===b.dataset.accessId),approve=b.dataset.approved==='true',role=b.dataset.role;const action=!approve?'Revoke access for':role==='leader'?'Grant full leader access, including private records, to':'Grant read-only member access to';if(!confirm(action+' '+m.display_name+' ('+m.email+')?'))return;b.disabled=true;const {error}=await Church.client.rpc('church_manage_member',{p_user_id:m.user_id,p_approved:approve,p_role:role});if(error)Church.message(error.message);else Church.message('Access updated.');await Church.refreshIdentity();await fetchMembers();});
}
window.addEventListener('church-identity',async()=>{const key=[Church.user?.id||'',Church.member?.approved||false,Church.member?.role||''].join('/');if(key!==lastIdentity){lastIdentity=key;notices=[];memberRows=[];editingNotice=null;manageMode=false;byId('membersPanel').hidden=true;byId('membersPanel').replaceChildren();if(byId('announcementDialog').open)byId('announcementDialog').close();byId('announcementDialog').replaceChildren();drawNotices();}
 byId('accountSlot').innerHTML=Church.authButton();Church.wireAuth();byId('leaderTools').hidden=!Church.isLeader();byId('toggleManage').textContent=manageMode?'Show public view':'Show drafts & scheduled';if(!Church.configured){byId('connectionState').textContent='Not connected · one-time setup required';byId('connectionState').classList.add('error');byId('lastUpdated').textContent='No shared notices are live until setup is completed.';drawNotices();return;}
 if(Church.client&&!subscribed){subscribed=true;Church.subscribe('church_announcements',fetchNotices);Church.subscribe('church_members',()=>Church.refreshIdentity());}
 if(Church.online)await fetchNotices();else{byId('connectionState').textContent='Offline / connection unavailable — displayed notices may be out of date';byId('connectionState').classList.add('error');drawNotices();}});
setInterval(()=>{if(Church.client&&navigator.onLine)fetchNotices();},20000);
Church.start();
